src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fullName;

    /**
     * @ORM\Column(type="date")
     */
    private $birthDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * List of Tweets authored by this User
     * @ORM\OneToMany(targetEntity=Tweet::class, mappedBy="author")
     */
    private $tweets;

    /**
     * List of Tweets liked by this User
     * @ORM\ManyToMany(targetEntity=Tweet::class, inversedBy="likers")
     * @ORM\JoinTable("user_like_tweet")
     */
    private $likedTweets;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->tweets = new ArrayCollection();
        $this->likedTweets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(?string $fullName): self
    {
        $this->fullName = $fullName;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Tweet[]
     */
    public function getTweets(): Collection
    {
        return $this->tweets;
    }

    public function addTweet(Tweet $tweet): self
    {
        if (!$this->tweets->contains($tweet)) {
            $this->tweets[] = $tweet;
            $tweet->setAuthor($this);
        }

        return $this;
    }

    public function removeTweet(Tweet $tweet): self
    {
        if ($this->tweets->removeElement($tweet)) {
            // set the owning side to null (unless already changed)
            if ($tweet->getAuthor() === $this) {
                $tweet->setAuthor(null);
            }
        }

        return $this;
    }

    public function getAge() {

        if (!$this->birthDate) return null;

        $now = new \DateTime();

        $difference = $now->diff($this->birthDate);

        return $difference->y;

    }

    /**
     * @return Collection|Tweet[]
     */
    public function getLikedTweets(): Collection
    {
        return $this->likedTweets;
    }

    public function likeTweet(Tweet $likedTweet): self
    {
        if (!$this->likedTweets->contains($likedTweet)) {
            $this->likedTweets[] = $likedTweet;
        }

        return $this;
    }

    public function unlikeTweet(Tweet $likedTweet): self
    {
        $this->likedTweets->removeElement($likedTweet);

        return $this;
    }

    public function doesLike(Tweet $tweet): bool {
        return $this->likedTweets->contains($tweet);
    }

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Tweet;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Translation\Exception\NotFoundResourceException;

class UserController extends AbstractController
{
    /**
     * @Route("/members", name="app_user_list")
     */
    public function list(): Response
    {
        $users = $this->getDoctrine()->getRepository(User::class)->findAll();

        return $this->render('user/list.html.twig', ['users' => $users]);
    }

    /**
     * @Route("/user/{id}", name="app_user_profile")
     * @param int $id
     * @return Response
     */
    public function profile(int $id): Response
    {
        /**
         * @var User $user
         */
        $user = $this->getDoctrine()->getRepository(User::class)->find($id);

        if (empty($user)) {
            throw new NotFoundResourceException("Cet utilisateur n'existe pas");
        }

        $tweets = $this->getDoctrine()->getRepository(Tweet::class)->findByAuthor($user);

        return $this->render('user/profile.html.twig', [
            'user' => $user,
            'tweets' => $tweets,
        ]);
    }

    /**
     * @Route("/me", name="app_current_user_profile")
     */
    public function me(): Response
    {
        /**
         * @var User $user
         */
        $user = $this->getUser();

        return $this->redirectToRoute('app_user_profile', ['id' => $user->getId()]);
    }
}

templates/user/list.html.twig
{% extends "_layouts/default.html.twig" %}

{% block header %}
    <header class="bg-light p-5">
        <div class="container">
            <h1 class="h1"> Liste des membres de LinkedIn'frep</h1>
            <hr>
            <p class="lead">
                Plus on est de fous, plus on rit !
            </p>
        </div>
    </header>
{% endblock %}

{% block main %}
    <ul class="list-group">

        {% for user in users %}

            <li class="list-group-item">

                <div class="user">
                    <p class="username">
                        <a href="{{ path('app_user_profile', { id: user.id }) }}">
                        <strong>{{ user.username }}</strong>

                        {% if (user.fullName) %}
                         <span>({{ user.fullName }})</span>
                        {%  endif %}

                        </a>
                    </p>

                    <p class="createdAt">
                        <i>Inscrit le {{ user.createdAt | date('d/m/Y') }}</i>
                    </p>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/user/profile.html.twig
{% extends "_layouts/two-columns.html.twig" %}

{% block header %}
    <header class="bg-light p-5">
        <div class="container">
            <h1 class="h1"> {{ user.username }} </h1>
            <hr>
            <p class="lead">
               Inscrit le {{ user.createdAt | date('d/m/Y') }}
            </p>
        </div>
    </header>
{% endblock %}

{% block mainColumn %}

    <h2>Les derniers tweets de {{ user.username }}</h2>
    {% for tweet in tweets %}
        {% include "_partials/_tweet.html.twig" %}
    {% endfor %}
{% endblock %}



{% block sidebar %}

    <h2>A propos</h2>

    <ul class="list-group">
        <li class="list-group-item">
            <strong>Nom complet : </strong>{{ user.fullName }}
        </li>

        <li class="list-group-item">
            <strong>Age : </strong> {{ user.age is empty ? 'Non renseigné' : user.age ~ ' ans'  }}
        </li>
        <li class="list-group-item">
            <strong>Anniversaire : </strong>{{ user.birthDate ? user.birthDate | date('d/m/Y') : 'Non renseigné' }}
        </li>
    </ul>
{% endblock %}